/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },'washed-blue-50': '#f3f3ff',
        'washed-blue-100': '#dadaff',
        'washed-blue-200': '#',
        'washed-blue-300': '#759aff',
        'washed-blue-400': '#527cff',
        'washed-blue-500': '#3563ff',
        'washed-blue-600': '#2d57df',
        'washed-blue-700': '#1f448c',
        'washed-blue-800': '#143265',
        'washed-blue-900': '#0a1e47',
        'washed-purple-50': '#f8fdf8',
        'washed-purple-100': '#ebf9e8',
        'washed-purple-200': '#e1f6dd',
        'washed-purple-300': '#d3f2ce',
        'washed-purple-400': '#caf0c5',
        'washed-purple-500': '#bdecb6',
        'washed-purple-600': '#acd7a6',
        'washed-purple-700': '#86a881',
        'washed-purple-800': '#688264',
        'washed-purple-900': '#4f634c',
        'primary-blue-50': '#e1f0ff',
        'primary-blue-100': '#aad3ff',
        'primary-blue-200': '#81b2ff',
        'primary-blue-300': '#4888ff',
        'primary-blue-400': '#2564ff',
        'primary-blue-500': '#0040ff',
        'primary-blue-600': '#0032da',
        'primary-blue-700': '#0024a8',
        'primary-blue-800': '#001f86',
        'primary-blue-900': '#00154a',
        'primary-purple-50': '#f3ebff',
        'primary-purple-100': '#d5bcff',
        'primary-purple-200': '#bd95ff',
        'primary-purple-300': '#9d5eff',
        'primary-purple-400': '#7b3eff',
        'primary-purple-500': '#4f01ff',
        'primary-purple-600': '#4601e8',
        'primary-purple-700': '#3601b5',
        'primary-purple-800': '#2b008c',
        'primary-purple-900': '#20006b',
        'Neutrals/neutrals-1': '#ffffff',
        'Neutrals/neutrals-2': '#fafafc',
        'Neutrals/neutrals-3': '#f1f1f2',
        'Neutrals/neutrals-4': '#e7e7e8',
        'Neutrals/neutrals-5': '#d0d0d4',
        'Neutrals/neutrals-6': '#b9b7be',
        'Neutrals/neutrals-7': '#868489',
        'Neutrals/neutrals-8': '#55535f',
        'Neutrals/neutrals-9': '#403d4a',
        'Neutrals/neutrals-10': '#26232d',
        'Neutrals/neutrals-11': '#1f1e28',
        'Neutrals/neutrals-12': '#15131b',
        'Neutrals/neutrals-13': '#020012',
        'brand-washedPurple': '#cdcbee',
        'brand-washedBlue': '#a7d6de',
        'brand-primaryBlue': '#0058ff',
        'brand-primaryPurple': '#6f00ff',
        'brand-dark': '#030012',
        
        },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
