name: Labeler
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - ".github/labeler.yml"
      - ".github/labeler.yaml"
      - ".github/labeler.json"
      - ".github/labeler.js"
      - ".github/labeler.toml"
      - ".github/labeler.lua"
      - ".github/labeler"
      - ".github/labeler/**/*"
      - ".github/labeler/**/**/*"
      - ".github/labeler/**/**/**/*"
      - ".github/labeler/**/**/**/**/*"
      - ".github/labeler/**/**/**/**/**/*"
      - ".github/labeler/**/**/**/**/**/**/*"
      - ".github/labeler/**/**/**/**/**/**/**/*"
      - ".github/labeler/**/**/**/**/**/**/**/**/*"
      - ".github/labeler/**/**/**/**/**/**/**/**/**/*"
      - ".github/labeler/**/**/**/**/**/**/**/**/**/**/*"
      - ".github/labeler/**/**/**/**/**/**/**/**/**/**/**/**/*"
  schedule:
    - cron: "0 1 * * 1"

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - id: label-the-PR
        uses: actions/labeler@v5

      - id: run-frontend-tests
        if: contains(steps.label-the-PR.outputs.all-labels, 'frontend')
        run: |
          echo "Running frontend tests..."
        #Put your commands for running frontend tests here

      - id: run-backend-tests
        if: contains(steps.label-the-PR.outputs.all-labels, 'backend')
        run: |
          echo "Running backend tests..."
        # Put your commands for running backend tests here
      # Label PRs 1, 2, and 3
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
